### ISSUE TITLE
question about the dice metrix

### ISSUE THREAD

**Issue by zhangliutong** [dykuang/Medical-image-registration#11]
I find that you calculate the dice based on the label list, and then average each part of a sub-region.Why not first fuse all labels into the five rois, and then calculate the dice?

**Comment by zhangliutong** [comment]
Besides, I wonder why you just use the 25 cortical regions(label_list_25) not all 31 regions of the five ROIs

**Comment by dykuang** [comment]
We think dice calculated on each labels would yield a more detailed and more strict measure on "small" regions. The suggestion calculating dice on fused labels certainly can be used, it will actually give higher dice scores in most cases since the region now is larger. Local miss alignments among those smaller labels will not be taken into account when they are fused into one. 

For your second question, as far as I can recall, there did not seem to be a particular reason. We just started with the 25 labels, you can also make the calculation on the 31 regions.

**Comment by zhangliutong** [comment]
Thank you so much!
