### ISSUE TITLE
I'm a little bit confused about your loss function!

### ISSUE THREAD

**Issue by white-hy** [dykuang/Medical-image-registration#7]
Hi! Dear Author. I'm studying your paper<FAIM – A ConvNet Method for Unsupervised
3D Medical Image Registration>.
I'm a little confused about your loss function. 
1. What does `-1` in the little box mean?
![image](https://user-images.githubusercontent.com/33248778/68655217-96a09500-056a-11ea-9ecd-ad4214cd2527.png)

Looking forward to your reply, thank you

**Comment by dykuang** [comment]
It means inverse: $\phi^{-1}$. Because the transformation $\phi$'s left action on the source S is defined by by its inverse, i.e. $\phi \dot S := S\circ \phi^{-1}$. Mathematics aside, you can simply take $\phi^{-1}$ as the transformation need to warp S towards T. In the code, $\phi^{-1}$ is approximated by $id+u$ where u is the learned displacement field.

**Comment by white-hy** [comment]
@dykuang Thank you very much for you reply. I can understand the meaning of `-1 `
As for `D` in the `R1(u)` and `R2(u)`, does it means `Displacement`?

**Comment by dykuang** [comment]
D is for the differential operator or derivative. Since the transformation is from R3 to R3, the first derivative is the 3 by 3 Jacobian matrix.

**Comment by white-hy** [comment]
@dykuang Thank you very much. You answer is very useful for me.
